### PR TITLE
Adding  Making Your Code Citable

### PR DESCRIPTION
**Pull request by stain**
See https://twitter.com/soilandreyes/status/1375500267890864138

### CODE REVIEW

**Comment by danielskatz** [comment]
I like this guide, but it's not a product of the FORCE11 group, so it should be added to the section further down, not the group's products section.

**Comment by stain** [comment]
How about we call teh section "Outreach and guides" instead of "Products"? 

Most people coming from outside F11 would here think of products as being something they could install or buy, not academic papers.

**Comment by danielskatz** [comment]
This is a page for the group, so I want to clearly show what the group has accomplished, along with related things done outside the context of the group.  (which I hope is a gentle way of saying no :) )

**Comment by danielskatz** [comment]
I'll go ahead and add this below

**Pull request closed without merging**
