### PR TITLE
Publications on FAIR principles for research software

### PR DESCRIPTION
**Pull request by stain**
See https://twitter.com/soilandreyes/status/1375497523134074883 and https://twitter.com/soilandreyes/status/1375497348407820299

### CODE REVIEW

**Comment by danielskatz** [comment]
Again, these are not products of this group, so they could be listed below as related. (along with https://arxiv.org/abs/2101.10883 and the other FAIR one I accidentally put in this section and will now move)

**Comment by stain** [comment]
https://arxiv.org/abs/2006.08589 by Leipzig also has an overview of different ways metadata and software go hand in hand with citations, not sure if/where it fits in here.

**Comment by danielskatz** [comment]
I'll put these in via another change

**Comment by stain** [comment]
I suggested moving them in 8d4f908c2527d36c753f20a8a6c555d4bcdc3a20 - also added Leipzig there.

**Comment by danielskatz** [comment]
sorry, I missed 
> https://arxiv.org/abs/2006.08589 by Leipzig also has an overview of different ways metadata and software go hand in hand with citations, not sure if/where it fits in here.

I'm not sure where it goes either, but if you figure out, please provide another PR...

**Pull request closed without merging**
