### PR TITLE
updated diagram files

### PR DESCRIPTION
**Pull request by dbouquin**
Updated final diagrams

### CODE REVIEW

**Comment by dbouquin** [comment]
Updated diagrams for A&P doc

**Comment by dbouquin** [comment]
final diagrams for A&P doc

**Comment by danielskatz** [comment]
why rename the file?  I made it readme.md so that it loaded from https://github.com/force11/force11-sciwg/tree/master/Challenges without having to add a filename at the end of the URL

**Comment by dbouquin** [comment]
Sorry about that. Hadn't even been thinking about it. Changed it back to readme. Also sort of gave up on getting the in-text anchors to work.

**Comment by danielskatz** [comment]
let's see how it looks now - can always try to fix again later...

**Pull request merged**
